<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE etmfschema [
        <!ELEMENT etmfschema (name, studyid, (node)*)>
        <!ELEMENT node (index, name, (node)*)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT studyid (#PCDATA)>
        <!ELEMENT index (#PCDATA)>
        ]>
<etmfschema>
    <name>DIA Schema</name>
    <studyid>10002</studyid>
        <node>
            <index>1</index>
            <name>01 Trial Management</name>
                <node>
                    <index>1.1</index>
                    <name>01.01 Trial Oversight</name>
                        <node>
                            <index>1.1.1</index>
                            <name>01.01.01 Trial Master File Plan</name>
                        </node>
                        <node>
                            <index>1.1.2</index>
                            <name>01.01.02 Trial Management Plan</name>
                        </node>
                </node>
                <node>
                    <index>1.2</index>
                    <name>01.02 Trial Team</name>
                        <node>
                            <index>1.2.1</index>
                            <name>01.02.01 Trail Team Details</name>
                        </node>
                        <node>
                            <index>1.2.2</index>
                            <name>01.02.02 Trail Team Curriculum Vitae</name>
                        </node>
                </node>
        </node>
        <node>
            <index>2</index>
            <name>02 Central Trial Documents</name>
                <node>
                    <index>2.1</index>
                    <name>02.01 Product and Trial Documentation</name>
                        <node>
                            <index>2.1.1</index>
                            <name>02.01.01 Investigators Brochure</name>
                        </node>
                        <node>
                            <index>2.1.2</index>
                            <name>02.01.02 Protocol</name>
                        </node>
                </node>
                <node>
                    <index>2.2</index>
                    <name>02.02 Subject Documentation</name>
                        <node>
                            <index>2.2.1</index>
                            <name>02.02.01 Subject Diary</name>
                        </node>
                        <node>
                            <index>2.2.2</index>
                            <name>02.02.02 Subject Questionnaire</name>
                        </node>
                </node>
        </node>
</etmfschema>

